[build-system]
requires = [
    "setuptools >= 35.0.2",
	"wheel",
]
build-backend = "setuptools.build_meta"

[tool.flake8]
extend-ignore = "E501"

[tool.isort]
src_paths = ["src/"]
multi_line_output = 4
